import {StyleSheet} from 'react-native';

export const globalColors = {
  primaryL: '#B2DE98',
  // primary: '#5DB12B',
  // primary: '#276800',
  // primaryD: '#276800',
  primary: '#279500',
  primaryD: '#279500',
  text: '#323232',
  background: '#f2f2f2',
  backgroundD: '#323232',
  muted: 'rgba(0, 0, 0, 0.5)',
};

export const globalStyles = StyleSheet.create({
  positionRelative: {position: 'relative'},
  positionAbsolute: {position: 'absolute'},
  h100: {height: '100%'},
  w100: {width: '100%'},
  m0: {margin: 0},
  mt10: {marginTop: 10},
  mt20: {marginTop: 20},
  mt40: {marginTop: 40},
  mt50: {marginTop: 50},
  mb10: {marginBottom: 10},
  mb20: {marginBottom: 20},
  mb40: {marginBottom: 40},
  mb50: {marginBottom: 50},
  mb80: {marginBottom: 80},
  ml5: {marginLeft: 5},
  ml10: {marginLeft: 10},
  mr10: {marginRight: 10},
  p0: {padding: 0},
  pt10: {paddingTop: 10},
  pt15: {paddingTop: 15},
  pt20: {paddingTop: 20},
  pt50: {paddingTop: 50},
  pb10: {paddingBottom: 10},
  pb15: {paddingBottom: 15},
  pb20: {paddingBottom: 20},
  pl10: {paddingLeft: 10},
  pl15: {paddingLeft: 15},
  pl20: {paddingLeft: 20},
  pr10: {paddingRight: 10},
  pr20: {paddingRight: 20},
  flexRow: {flexDirection: 'row'},
  centeredContent: {alignItems: 'center', justifyContent: 'center'},
  justifyContentBetween: {justifyContent: 'space-between'},
  justifyContentEnd: {justifyContent: 'flex-end'},
  alignItemsCenter: {alignItems: 'center'},
  alignItemsEnd: {alignItems: 'flex-end'},
  alignItemsBaseline: {alignItems: 'baseline'},
  flex1: {flex: 1},
  flex00: {flexGrow: 0, flexShrink: 0},
  flex11: {flexGrow: 1, flexShrink: 1},
  border: {borderWidth: 1, borderColor: 'brown'},
  rounded: {borderRadius: 10},
  bgWhite: {backgroundColor: 'white'},
  bgBackgroundD: {backgroundColor: globalColors.backgroundD},
  h1: {fontSize: 22},
  h2: {fontSize: 22},
  h3: {fontSize: 10},
  f20: {fontSize: 20},
  fDefault: {fontSize: 14},
  // h4: {fontSize: },
  // h5: {fontSize: },
  // h6: {fontSize: },
  b1: {fontWeight: "100"},
  b2: {fontWeight: "200"},
  b3: {fontWeight: "300"},
  b4: {fontWeight: "400"},
  b5: {fontWeight: "500"},
  b6: {fontWeight: "600"},
  b7: {fontWeight: "700"},
  b8: {fontWeight: "800"},
  b9: {fontWeight: "900"},
  textCenter: {textAlign: 'center'},
  textTitleCase: { textTransform: 'capitalize'},
  textBlack: {color: 'black'},
  textWhite: {color: 'white'},
  textDanger: {color: 'red'},
  textMuted: {color: globalColors.muted},
  textPrimary: {color: globalColors.primary},
  textPrimaryD: {color: globalColors.primaryD}
});
